apiVersion: v1
kind: Pod
metadata:
  name: expense
spec:
  containers:
  - name: naresh-pod1
    image: naresh34/frontend:v1
    ports: 
    - containerPort: 80 
  nodeSelector:
    env: dev    
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "dev"
    effect: "NoSchedule"