apiVersion: v1
kind: Pod
metadata:
  name: expense
spec:
  nodeSelector:
    env: dev
  containers:  
  - name: naresh-pod1
    image: naresh34/frontend:v1
    ports: 
    - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - dev 