apiVersion: v1
kind: Pod
metadata:
  name: expense2
spec:
  containers:
  - name: naresh-pod1
    image: naresh34/frontend:v1
    ports: 
    - containerPort: 2 
    affinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value     
