apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  labels:
    name: naresh
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - naresh
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---    
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: naresh
              operator: In
              values:
              - santhosh
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80