apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-grantor-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-grantor
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: naresh
---
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::796973477223:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-57hxeNJLSisv
      username: system:node:{{EC2PrivateDNSName}}
   mapUsers: |
    - groups:
      - pod-reader
      userarn: arn:aws:iam::796973477223:user/naresh
      username: naresh   
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-27T15:26:49Z"
  name: aws-auth
  namespace: kube-system
  uid: 2ddbd138-7df6-4d37-88e1-3623745c1677
